[games-engines/frobtads] fork ebuild to fix compilation
Gentoo bug 602446.

.../x86_64-pc-linux-gnu/bin/ld: src/frob-frobtadsappcurses.o: undefined reference to symbol 'meta'
/lib64/libtinfo.so.6: error adding symbols: DSO missing from command line